### ISSUE TITLE
What is this about 2FA code

### ISSUE THREAD

**Issue by mohdsofian91** [niccokunzmann/download_latest#8]
I dont understand about 2FA code

**Comment by niccokunzmann** [comment]
This may not be related to this module/repository. You will probably find understanding on wikipedia or the github help.

**Comment by BRANDEN529** [comment]
> I dont understand about 2FA code

Its a way to double check its you signing in you have gave go down load an authentication app and put in a coffee from the d I site you're trying to log into and every time you login you have to go into that app and get the code that's showing at that time of changes every 60 Seconds so that they can guarantee that it is you and not a robot or a hacker that is trying to sign in

**Comment by niccokunzmann** [comment]
@mohdsofian91 , does this answer your question?

**Comment by niccokunzmann** [comment]
@mohdsofian91 , does this answer your question?

**Comment by Ekkarat30** [comment]
Why can't login

**Comment by niccokunzmann** [comment]
Please contact the GitHub Support.

Am 29.12.20 um 05:30 schrieb ekkarat_product:

**Comment by Ekkarat30** [comment]
Please support me auto repair to my account.
